---
- name: ensure the proxmox repo is configured
  copy:
    content: "deb http://download.proxmox.com/debian/pve {{ ansible_lsb['codename'] }} pve-no-subscription"
    dest: /etc/apt/sources.list.d/pve-install-repo.list
    owner: root
    group: root
    mode: 0644
  register: proxmox_repo
  tags:
    - proxmox

- name: ensure the proxmox repo key is present
  get_url:
    url: http://download.proxmox.com/debian/proxmox-ve-release-5.x.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-ve-release-5.x.gpg
    owner: root
    group: root
    mode: 0644
  register: proxmox_gpg
  tags:
    - proxmox

- name: update apt cache
  apt:
    update_cache: yes
  when: proxmox_repo is changed or proxmox_gpg is changed
  tags:
    - proxmox

- name: ensure the required packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - proxmox-ve
    - open-iscsi
  tags:
    - proxmox

- name: ensure the iscsi initiator name is configured
  lineinfile:
    dest: /etc/iscsi/initiatorname.iscsi
    regexp: "InitiatorName="
    line: "InitiatorName=iqn.2018-06.net.dubzland:{{ inventory_hostname }}"
    state: present
  notify:
    - restart iscsid
  tags:
    - proxmox

