---
- name: ensure gnupg is available for apt_key
  apt:
    name: gnupg
    state: present
  tags:
    - proxmox

- name: ensure the proxmox repo keys are present
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "{{ dubzland_proxmox_gpg_keys }}"
  tags:
    - proxmox

- name: ensure the proxmox repo is configured
  apt_repository:
    repo: "deb {{ dubzland_proxmox_repo_url }} {{ ansible_lsb['codename'] }} {{ dubzland_proxmox_repo_name }}"
    state: present
    update_cache: true
  tags:
    - proxmox

- name: ensure the required packages are installed
  apt:
    name: "{{ dubzland_proxmox_packages }}"
    state: present
    install_recommends: false
  tags:
    - proxmox
